### ISSUE TITLE
Seafile Pro Template is blacklisted 

### ISSUE THREAD

**Issue by jkasten80** [chirmstream/unraid-templates#8]
Hey, i installed the seafile pro on my unraid server. I couldnt find the template so i uploaded it manual. Now i see that the template is blacklisted. Are there any problems regarding this?

**Comment by chirmstream** [comment]
It is because you have to create an account and login to their docker registry to pull the image.  The community app store isn't automated to do that, so when it tries to pull the image it fails - which is what caused the blacklist.  

You shouldn't have any issues using the template.  When the next version is released, you will have to update the tag, but it is an easy change when it comes time to do so.

**Comment by jkasten80** [comment]
Thx, great work anyway. I have been waiting for a template like this since ages... :-D
